services:
  # PHP
  resetter-bundle-php83:
    container_name: resetter-bundle-php83
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.3-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - BOX_REQUIREMENT_CHECKER=0

  resetter-bundle-php84:
    container_name: resetter-bundle-php84
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.4-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - BOX_REQUIREMENT_CHECKER=0

  resetter-bundle-php85:
    container_name: resetter-bundle-php85
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_TAG: 8.5-fpm
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - BOX_REQUIREMENT_CHECKER=0
